spring:
  profiles.active: oracle
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:oracle:thin:@${DB_SERVER}/xe
    username: system
    password: oracle
#    url: jdbc:postgresql://${DB_SERVER}:5432/twitter_postgres
#    username: postgres
#    password: postgres
    hikari:
      connection-test-query: select 1 from dual
      pool-name: TransactionsAPIHikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true