global:
  scrape_interval:   15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'bootifull-monitoring'

scrape_configs:
- job_name:       'Twitter-App'
  scrape_interval: 10s
  metrics_path: 'tweetsvcs/actuator/prometheus'
  static_configs:
  - targets: ['twitter-app-3:8110']
    labels:
      application: 'Twitter-App'

#  - job_name:       'monitoring-tomcat'
#    scrape_interval: 10s
#    metrics_path: 'tweetsvcs/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:9010']
#        labels:
#          application: 'monitoring-tomcat'

- job_name:       'monitoring-demo-go'
  scrape_interval: 10s
  metrics_path: '/prometheus'
  static_configs:
    - targets: ['twitter-go-app:8500']
      labels:
        application: 'go-app-123'

#- job_name:       'Oracle DB'
#  # Override the global default and scrape targets from this job every 10 seconds.
#  scrape_interval: 10s
#  metrics_path: '/metrics'
#
#  static_configs:
#    - targets: ['db_exporter:9161']
#      labels:
#        application: 'oracle'

- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']
